server:
  port: 8079
spring:
 
  data:
    mongodb:
      host: localhost
      port: 27017
      database: TweetApp
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    
  application:
    name: media-service
    
   
